language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t moopzdev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true moopzdev/docker-react npm run test
